using System.Collections.Generic;
using System.Linq;
using Items;
using Units.Recursos;
using System.Diagnostics;

namespace Units.Buffs
{
	/// <summary>
	/// Represents the buff generated by the equipment
	/// </summary>
	public class EquipBuff : IStatsBuff
	{
		readonly ICollection<IEquipment> equipment;

		bool IBuff.IsVisible { get { return false; } }

		/// <summary>
		/// Gets the buff maanger that this will affect
		/// </summary>
		/// <value>The buff manager.</value>
		public BuffManager BuffManager { get; set; }

		/// <summary>
		/// Gets the resoruce manager.
		/// </summary>
		public ManejadorRecursos RecManager { get; }

		/// <summary>
		/// Devuelve la modificación (absoluta) de valor de un recurso.
		/// </summary>
		/// <returns>The delta.</returns>
		/// <param name="resName">Res name.</param>
		public float StatDelta (string resName)
		{
			var ret = 0f;
			foreach (var x in equipment.OfType<IBuffGenerating> ())
			{
				foreach (var buffEntry in x.GetDeltaStat ())
				{
					if (buffEntry.Key == resName)
					{
						ret += buffEntry.Value;
						break;
					}
				}
			}
			return ret;
		}

		#region IBuff implementation

		/// <summary>
		/// Se invoca cuando está por desanclarse
		/// </summary>
		public void Terminating ()
		{
		}

		/// <summary>
		/// De invoca justo después de anclarse.
		/// </summary>
		public void Initialize ()
		{
		}

		/// <summary>
		/// Nombre
		/// </summary>
		/// <value>The nombre.</value>
		public string Nombre { get { return "Equipment"; } }

		/// <summary>
		/// Devuelve la textura a usar
		/// </summary>
		/// <value>The name of the base texture.</value>
		public string BaseTextureName { get { return null; } }

		BuffManager IBuff.Manager
		{
			get { return BuffManager; }
			set { BuffManager = value; }
		}

		#endregion

		#region IInternalUpdate implementation

		/// <summary>
		/// Updates the buff.
		/// Does nothing
		/// </summary>
		public void Update (float gameTime)
		{
		}

		#endregion

		/// <summary>
		/// Returns a <see cref="System.String"/> that represents the current <see cref="Units.Buffs.EquipBuff"/>.
		/// </summary>
		/// <returns>A <see cref="System.String"/> that represents the current <see cref="Units.Buffs.EquipBuff"/>.</returns>
		public override string ToString ()
		{
			return string.Format (
				"[EquipBuff: equipment={0}, BuffManager={1}, RecManager={2}, Nombre={3}]",
				equipment,
				BuffManager,
				RecManager,
				Nombre);
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="Units.Buffs.EquipBuff"/> class.
		/// </summary>
		/// <param name="eqs">The equipment</param>
		public EquipBuff (ICollection<IEquipment> eqs)
		{
			equipment = eqs;
		}
	}
}